const DEMO_MODEL_REGISTRY = [
  { id:'gpt-5-nano', providerId:'openai', name:'GPT', family:'GPT', version:'GPT-5 nano', cls:'model-gpt' }, { id:'gpt-6-astra', providerId:'openai', name:'GPT', family:'GPT', version:'GPT-6 Astra', cls:'model-gpt' }, { id:'gpt-5.6-luna', providerId:'openai', name:'GPT', family:'GPT', version:'GPT-5.6 Luna', cls:'model-gpt' }, { id:'gpt-5.6-sol', providerId:'openai', name:'GPT', family:'GPT', version:'GPT-5.6 Sol', cls:'model-gpt' }, { id:'gpt-5.6-terra', providerId:'openai', name:'GPT', family:'GPT', version:'GPT-5.6 Terra', cls:'model-gpt' },
  { id:'claude-haiku-4-5', providerId:'anthropic', name:'Claude', family:'Claude', version:'Claude Haiku 4.5', cls:'model-claude' }, { id:'claude-sonnet-5', providerId:'anthropic', name:'Claude', family:'Claude', version:'Claude Sonnet 5', cls:'model-claude' }, { id:'claude-fable-5', providerId:'anthropic', name:'Claude', family:'Claude', version:'Claude Fable 5', cls:'model-claude' }, { id:'claude-fable-5-1', providerId:'anthropic', name:'Claude', family:'Claude', version:'Claude Fable 5.1', cls:'model-claude' }, { id:'claude-opus-5', providerId:'anthropic', name:'Claude', family:'Claude', version:'Claude Opus 5', cls:'model-claude' },
  { id:'gemini-3.5-flash-lite', providerId:'google', name:'Gemini', family:'Gemini', version:'Gemini 3.5 Flash-Lite', cls:'model-gemini' }, { id:'gemini-3.6-flash', providerId:'google', name:'Gemini', family:'Gemini', version:'Gemini 3.6 Flash', cls:'model-gemini' }, { id:'gemini-3.7-flash', providerId:'google', name:'Gemini', family:'Gemini', version:'Gemini 3.7 Flash', cls:'model-gemini' }, { id:'gemini-3.8-flash', providerId:'google', name:'Gemini', family:'Gemini', version:'Gemini 3.8 Flash', cls:'model-gemini' },
  { id:'qwen3-local', providerId:'ollama-qwen', name:'Qwen', family:'Qwen', version:'Qwen3 14B', cls:'model-qwen' }, { id:'qwen35-local', providerId:'ollama-qwen', name:'Qwen', family:'Qwen', version:'Qwen3.5 9B', cls:'model-qwen' }, { id:'deepseek-r1-local', providerId:'ollama-deepseek', name:'DeepSeek', family:'DeepSeek', version:'DeepSeek-R1 14B', cls:'model-deepseek' }, { id:'gemma4-local', providerId:'ollama-gemma', name:'Gemma', family:'Gemma', version:'Gemma 4 12B', cls:'model-gemma' }, { id:'glm4-local', providerId:'ollama-glm', name:'GLM', family:'GLM', version:'GLM-4 9B', cls:'model-glm' }
];
const registeredModels = window.aiBrowserModels || window.__AI_BROWSER_MODELS__ || window.aiBrowser?.models;
const MODEL_REGISTRY = (Array.isArray(registeredModels) && registeredModels.length ? registeredModels : DEMO_MODEL_REGISTRY).map(model => typeof model === 'string' ? { name:model, family:model.split(/[\s-]+/)[0] } : { ...model, name:model.name || model.id || model.model, family:model.family || model.company || model.provider || model.name });
const sampleLogIds = new Set(['001', '002', '003']);
const importedLogs = window.AI_DEBATE_IMPORTED_LOGS || [];
const localMigrationLogs = (() => { try { const value = JSON.parse(localStorage.getItem('ai-debate-logs') || '[]'); return Array.isArray(value) ? value.filter(log => log && log.id != null && !sampleLogIds.has(String(log.id))) : []; } catch (_) { return []; } })();
let logs = [...importedLogs].filter((log, index, all) => all.findIndex(item => item.id === log.id) === index);
const builtInLogIds = new Set([...importedLogs.map(log => String(log.id)), ...sampleLogIds]);
let dataReady = false; let dataError = '';
function getPublishedLogs(){ return logs.filter(log => log && log.id != null && !builtInLogIds.has(String(log.id))); }
function normalizeRemoteLog(log){ return { ...log, id:String(log.id), participants:Array.isArray(log.participants)?log.participants:[], turns:Array.isArray(log.turns)?log.turns:[], critique:String(log.critique||''), memo:String(log.memo||''), raw:String(log.raw||'') }; }
function formatDataError(error){ return `公開ログを読み込めませんでした。Supabaseの設定または接続を確認してください。${error?.message ? ` (${error.message})` : ''}`; }
const app = document.querySelector('#app');
const modelData = name => { const value = String(name || ''); const match = MODEL_REGISTRY.find(m => value.toLowerCase().includes(String(m.name || m.family || '').toLowerCase()) || value.toLowerCase().includes(String(m.family || '').toLowerCase())); return match || { family:value.split(/[\s-]+/)[0], cls:'' }; };
const modelHTML = name => `<span class="model ${modelData(name).cls}">${escapeHTML(name)}</span>`;
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const families = () => ['All', ...new Set([...logs.flatMap(l => [...l.participants, l.judge]), ...MODEL_REGISTRY.map(m => m.family || m.name)].map(n => modelData(n).family).filter(Boolean))];
function render() { const path = location.hash.replace(/^#\/?/, '').split('?')[0]; if(path.startsWith('log/')) return renderDetail(path.slice(4)); if(path==='logs') return renderLogs(); if(path==='about') return renderAbout(); if(path==='admin') return renderAdmin(); return renderHome(); }
function renderHome() { app.innerHTML = `<section class="home"><div class="home-visual"><img src="assets/gpt-chan-mascot.png" alt="" /></div><div class="home-copy"><p class="home-kicker">A personal archive of machine-to-machine debate</p><h1>AI Debate Archive</h1><p>AI同士のディベートとJudge AIの批評を、年月とともに残す。</p><div class="home-actions"><a class="text-link" href="#/logs">Read the logs</a><a class="text-link" href="#/about">About this archive</a></div></div></section>`; }
function renderLogs() {
  if(!dataReady) return app.innerHTML='<section><p class="eyebrow">Archive</p><h1>Logs</h1><p class="admin-note">公開ログを読み込んでいます…</p></section>';
  if(dataError) return app.innerHTML=`<section><p class="eyebrow">Archive</p><h1>Logs</h1><p class="auth-error" role="alert">${escapeHTML(dataError)}</p></section>`;
  const qs = new URLSearchParams(location.hash.split('?')[1] || '');
  const filter = qs.get('filter') || 'All';
  const fs = families();
  const visible = logs.filter(l => filter==='All' || [...l.participants,l.judge].some(n => modelData(n).family===filter));
  const pages = Math.max(1, Math.ceil(visible.length / 30));
  const requestedPage = Number(qs.get('page') || 1);
  const page = Number.isInteger(requestedPage) ? Math.min(pages, Math.max(1, requestedPage)) : 1;
  const shown = visible.slice((page-1)*30, page*30);
  const pageLink = p => `#/logs?filter=${encodeURIComponent(filter)}&page=${p}`;
  app.innerHTML = `<section><div class="section-head"><div><p class="eyebrow">Archive</p><h1>Logs</h1></div><span class="meta">${visible.length} entries</span></div><div class="filters" aria-label="Filter by model family">${fs.map(f=>`<a class="filter ${f===filter?'active':''}" href="#/logs?filter=${encodeURIComponent(f)}&page=1">${escapeHTML(f)}</a>`).join('')}</div><div class="log-list">${shown.map(l=>`<a class="log-row" href="#/log/${l.id}"><div class="log-title">${escapeHTML(l.title)}</div><div class="log-meta"><span class="log-models">${l.participants.map(modelHTML).join(' · ')} <span> / Judge: ${modelHTML(l.judge)}</span></span><span class="log-date">${escapeHTML(l.date)}</span></div></a>`).join('') || '<p class="empty">No logs in this filter.</p>'}</div><div class="pagination">${Array.from({length:pages},(_,i)=>`<a class="${page===i+1?'active':''}" href="${pageLink(i+1)}">${i+1}</a>`).join('')}${page<pages?`<a href="${pageLink(page+1)}">Next</a>`:''}</div></section>`;
}
function turnSystemHTML(turn,index,turns){ const speaker=turn[0]; const speakerTurn=turns.slice(0,index+1).filter(item=>item[0]===speaker).length; const speakerTotal=turns.filter(item=>item[0]===speaker).length; return `<div class="turn-system"><span>SYSTEM</span> 全体 ${index+1} / ${turns.length}・${modelHTML(speaker)} ${speakerTurn} / ${speakerTotal}</div>`; }
function renderTurn(turn,index,turns){ const [speaker,body]=turn; return `<div class="turn"><div class="turn-speaker">${modelHTML(speaker)}</div><div class="turn-body">${escapeHTML(body)}</div>${turnSystemHTML(turn,index,turns)}</div>`; }
function renderDetail(id) { if(!dataReady) return app.innerHTML='<section><p class="admin-note">公開ログを読み込んでいます…</p></section>'; if(dataError) return app.innerHTML=`<section><p class="auth-error" role="alert">${escapeHTML(dataError)}</p></section>`; const l=logs.find(x=>String(x.id)===String(id)); if(!l) return app.innerHTML='<p class="empty">This log was not found.</p>'; app.innerHTML=`<article class="prose"><a class="meta" href="#/logs">← Logs</a><p class="eyebrow" style="margin-top:2rem">ディベートのテーマ</p><h1>${escapeHTML(l.title)}</h1><dl class="detail-meta"><div><dt>Participants</dt><dd>${l.participants.map(modelHTML).join(' · ')}</dd></div><div><dt>Judge</dt><dd>${modelHTML(l.judge)}</dd></div><div><dt>Turns</dt><dd>${l.turns.length}</dd></div><div><dt>Date</dt><dd>${escapeHTML(l.date)}</dd></div></dl><section><h2>Debate</h2>${l.turns.map((t,index)=>renderTurn(t,index,l.turns)).join('')}</section><section class="subsection judge-critique"><h2>Judge critique</h2><div class="judge-critique-speaker"><span class="meta">Judge</span> ${modelHTML(l.judge)}</div>${critiqueHTML(l.critique)}</section>${l.memo?`<section class="subsection"><h2>Personal Memo</h2><p class="memo">${escapeHTML(l.memo)}</p></section>`:''}</article>`; }
function renderAbout() { app.innerHTML=`<article class="prose"><p class="eyebrow">About</p><h1>AI Debate Archive</h1><p>このサイトはAI同士のディベートとJudge AIの批評を残す個人アーカイブです。</p><p>AIモデルは更新が速いため年月を残し、「その時点でそのモデルがどう考え、どう議論していたか」を後から読めるようにします。</p><p class="eyebrow">その時代、そのモデル世代の思考を残すためのログアーカイブ。</p><section class="subsection"><h2>Debate rules</h2><ul><li>6 turns = 各AI 3回</li><li>8 turns = 各AI 4回</li><li>10 turns = 各AI 5回</li><li>Blind Modeでは参加AIは相手モデルの正体を知らない。</li><li>1投稿は最大2000日本語文字程度。</li><li>Judge AIはディベート後に別途評価・批評する。</li></ul></section><section class="subsection"><h2>Model context</h2><p>この環境ではclosed/cloudモデルはWeb検索や外部ツールを使う場合があり、open/localモデルは通常ネット検索なしで回答します。そのため、利用可能な情報やツールの差が議論内容に影響し得ます。このアーカイブでは、その差も含めて当時の記録として扱います。</p></section><section class="subsection"><h2>Raw log policy</h2><p class="raw-log-policy">このアーカイブでは、ローカルモデルを含む各AIの出力を、原則として生成時のまま保存します。\nハルシネーション、事実誤認、文法上の崩れ、途中で英語や中国語など別言語へ切り替わった出力についても、後から内容を訂正・整形して置き換えることはしません。\nこれは、各モデルがその時点で実際にどのように応答したかを記録することを優先しているためです。</p></section><section class="subsection contact-section"><h2>Contact</h2><form class="contact-form" action="https://formsubmit.co/malmal39@outlook.jp" method="POST" accept-charset="UTF-8"><input type="hidden" name="_subject" value="AI Debate Archive contact"><input type="hidden" name="_template" value="table"><input type="hidden" name="_captcha" value="true"><div class="field"><label for="contact-name">Name <span class="field-note">(optional)</span></label><input id="contact-name" name="name" type="text" autocomplete="name"></div><div class="field"><label for="contact-email">Email <span class="field-note">(optional)</span></label><input id="contact-email" name="email" type="email" autocomplete="email"></div><div class="field"><label for="contact-subject">Subject</label><input id="contact-subject" name="subject" type="text" required></div><div class="field"><label for="contact-message">Message</label><textarea id="contact-message" name="message" required></textarea></div><button class="primary" type="submit">Send</button></form></section></article>`; }
let authClient=null; let authSession=null; let authReady=false;
function supabaseConfig(){ return window.AI_DEBATE_SUPABASE_CONFIG || {}; }
function renderAdmin(){ if(!authReady){ app.innerHTML='<section class="auth-panel"><p class="eyebrow">Private workspace</p><h1>Admin</h1><p class="admin-note">Checking authentication…</p></section>'; return; } if(!authSession){ app.innerHTML='<section class="auth-panel"><p class="eyebrow">Private workspace</p><h1>Admin</h1><p class="admin-note">Sign in with the administrator account to access this page.</p><form id="login-form" class="auth-form"><div class="field"><label for="login-email">Email</label><input id="login-email" type="email" autocomplete="username" required></div><div class="field"><label for="login-password">Password</label><input id="login-password" type="password" autocomplete="current-password" required></div><button class="primary" type="submit">Log in</button><p id="login-error" class="auth-error" role="alert"></p></form></section>'; const form=document.querySelector('#login-form'); form.onsubmit=async event=>{ event.preventDefault(); const errorBox=document.querySelector('#login-error'); errorBox.textContent=''; if(!authClient){ errorBox.textContent='Supabase Auth is not configured yet.'; return; } const {error}=await authClient.auth.signInWithPassword({email:document.querySelector('#login-email').value.trim(),password:document.querySelector('#login-password').value}); if(error) errorBox.textContent='ログインできませんでした。メールアドレスとパスワードを確認してください。'; }; return; } renderAdminWorkspace(); document.querySelector('#logout').onclick=async()=>{ if(authClient) await authClient.auth.signOut(); }; }
async function initializeAuth(){ const config=supabaseConfig(); try { if(!config.url || !config.anonKey || !window.supabase?.createClient) return; authClient=window.supabase.createClient(config.url,config.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}); authClient.auth.onAuthStateChange((_event,session)=>{ authSession=session; if(location.hash.replace(/^#\/?/,'').split('?')[0]==='admin') renderAdmin(); }); const {data,error}=await authClient.auth.getSession(); if(error) throw error; authSession=data?.session || null; } catch(error) { console.error('Supabase Auth initialization failed:',error); authSession=null; } finally { authReady=true; if(location.hash.replace(/^#\/?/,'').split('?')[0]==='admin') renderAdmin(); } }
async function loadPublicLogs(){ dataReady=false; dataError=''; if(!authClient){ dataError='Supabaseが設定されていないため、公開ログを取得できません。'; dataReady=true; render(); return; } try { const {data,error}=await authClient.from('debate_logs').select('*').order('date',{ascending:false}).order('created_at',{ascending:false}); if(error) throw error; logs=(data||[]).map(normalizeRemoteLog); } catch(error) { console.error('Supabase public log load failed:',error); dataError=formatDataError(error); } finally { dataReady=true; render(); } }
function adminArchiveHTML(){ const items=getPublishedLogs(); return `<section class="admin-archive"><div class="section-head"><div><p class="eyebrow">Published logs</p><h2>Stored debate threads</h2></div><span class="meta">${items.length} entries</span></div>${items.length?`<div class="admin-log-list">${items.map(log=>`<div class="admin-log-row"><div><div class="log-title">${escapeHTML(log.title||'Untitled')}</div><div class="log-meta">${log.participants?.map(modelHTML).join(' · ')||''} <span> / Judge: ${modelHTML(log.judge||'')}</span><span class="log-date">${escapeHTML(log.date||'')}</span></div></div><button class="delete-log" type="button" data-delete-log="${escapeHTML(log.id)}">Delete</button></div>`).join('')}</div>`:'<p class="empty">No published logs yet.</p>'}</section>`; }
async function deleteAdminLog(id){ const item=getPublishedLogs().find(log=>String(log.id)===String(id)); if(!item||!window.confirm(`「${item.title||'Untitled'}」を削除しますか？`)) return; const {error}=await authClient.from('debate_logs').delete().eq('id',id); if(error){ alert(`削除できませんでした: ${error.message}`); return; } logs=logs.filter(log=>String(log.id)!==String(id)); renderAdmin(); }
function downloadLocalMigration(){ const payload=JSON.stringify(localMigrationLogs,null,2); const blob=new Blob([payload],{type:'application/json'}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download='ai-debate-local-logs-migration.json'; link.click(); URL.revokeObjectURL(link.href); }
function renderAdminWorkspace() { app.innerHTML=`<section><div class="admin-session"><span>Signed in as ${escapeHTML(authSession?.user?.email || '')}</span><button type="button" id="logout">Log out</button></div><p class="eyebrow">Private workspace</p><h1>Admin</h1><p class="admin-note">AI Browserから貼り付けたログを解析し、確認してから公開アーカイブに保存します。元の貼り付け内容も保存します。</p><form id="admin-form"><div class="form-grid"><div class="field"><label for="title">Title</label><input id="title" required></div><div class="field"><label for="date">Year-month (YYYY-MM)</label><input id="date" pattern="\\d{4}-\\d{2}" placeholder="2026-09" required></div>${modelSelectHTML('model-a','Model A','Select Model A')}${modelSelectHTML('model-b','Model B','Select Model B')}${modelSelectHTML('judge','Judge','Select Judge')}<div class="field full"><label for="raw">Paste Debate Log</label><textarea id="raw" placeholder="GPT / GPT-6 Astra\n本文...\n\nSYSTEM\n全体 1 / 10・GPT / GPT-6 Astra 1 / 5\n\nJudge\n評価..."></textarea></div><div class="field full"><label for="memo">Personal Memo (optional)</label><textarea id="memo" style="min-height:110px"></textarea></div></div><div class="admin-actions"><button class="primary" type="button" id="parse">Parse & Preview</button><button type="submit">Publish</button><button type="button" id="migration">Download local migration</button></div></form><div id="preview" class="preview" hidden></div>${adminArchiveHTML()}</section>`; setupModelSelects(); document.querySelector('#parse').onclick=()=>preview(parseForm()); document.querySelector('#migration').onclick=downloadLocalMigration; document.querySelectorAll('[data-delete-log]').forEach(button=>button.onclick=()=>deleteAdminLog(button.dataset.deleteLog)); document.querySelector('#admin-form').onsubmit=async e=>{e.preventDefault(); const item=parseForm(); if(!item.title||!item.participants[0]||!item.participants[1]||!item.turns.length) return preview(item,'Title, both models, and at least one parsed turn are required.'); const publishButton=e.submitter; publishButton.disabled=true; item.id=crypto.randomUUID(); item.raw=document.querySelector('#raw').value; const {data,error}=await authClient.from('debate_logs').insert(item).select().single(); publishButton.disabled=false; if(error){ preview(item,`公開保存できませんでした。管理者権限またはSupabase設定を確認してください。 ${error.message}`); return; } const saved=normalizeRemoteLog(data||item); logs=[saved,...logs.filter(log=>String(log.id)!==String(saved.id))]; location.hash='#/log/'+saved.id; }; }
function modelProviderKey(model){ return String(model.providerId||model.provider||model.family||model.name||''); }
function modelProviderLabel(model){ return String(model.displayName||model.family||model.provider||model.name||''); }
function modelDetailLabel(model){ return String(model.version||model.name||model.id||model.model||''); }
function modelSelectHTML(id,label,placeholder){ const providers=[...new Map(MODEL_REGISTRY.map(model=>[modelProviderKey(model),model])).values()]; const firstProvider=modelProviderKey(providers[0]||{}); const providerOptions=providers.map(model=>`<option value="${escapeHTML(modelProviderKey(model))}">${escapeHTML(modelProviderLabel(model))}</option>`).join(''); const details=MODEL_REGISTRY.filter(model=>modelProviderKey(model)===firstProvider).map(model=>`<option value="${escapeHTML(modelDetailLabel(model))}">${escapeHTML(modelDetailLabel(model))}</option>`).join(''); return `<div class="field"><label for="${escapeHTML(id)}-provider">${escapeHTML(label)}</label><select id="${escapeHTML(id)}-provider" class="model-provider" data-model-target="${escapeHTML(id)}" aria-label="${escapeHTML(label)} AI name">${providerOptions}</select><select id="${escapeHTML(id)}" required aria-label="${escapeHTML(label)} model detail">${details}</select></div>`; }
function setupModelSelects(){ ['model-a','model-b','judge'].forEach(id=>{ const provider=document.querySelector(`#${id}-provider`); const detail=document.querySelector(`#${id}`); if(!provider||!detail) return; const update=()=>{ const models=MODEL_REGISTRY.filter(model=>modelProviderKey(model)===provider.value); detail.innerHTML=models.map(model=>`<option value="${escapeHTML(modelDetailLabel(model))}">${escapeHTML(modelDetailLabel(model))}</option>`).join(''); }; provider.onchange=update; update(); }); }
function parserNormalize(value){ return String(value||'').replace(/\s+/g,' ').trim().toLowerCase(); }
function parserProfile(id,key){ const detail=document.querySelector('#'+id)?.value.trim()||''; const provider=document.querySelector('#'+id+'-provider'); const family=provider?.selectedOptions?.[0]?.textContent.trim()||''; return {key,family,detail}; }
function parserSpeakerHeader(line,profiles){ const match=String(line||'').match(/^\s*([^/:：]{1,40})\s*\/\s*(.{2,160}?)\s*$/); if(!match) return null; const family=match[1].trim(); const detail=match[2].trim(); const profile=profiles.find(item=>parserNormalize(item.detail)===parserNormalize(detail)&&(!item.family||parserNormalize(item.family)===parserNormalize(family))); return profile ? {speaker:family+' / '+detail,profile:profile.key} : null; }
function parserIsSystemLine(line){ return /^\s*SYSTEM\s*$/i.test(String(line||'')); }
function parserIsProgressLine(line){ return /^\s*全体\s+\d+\s*\/\s*\d+\s*[・·]/.test(String(line||'')); }
function parserJudgeMarker(line,judgeProfile,participantProfiles=[]){ const text=String(line||'').trim(); const inline=text.match(/^\s*#*\s*(?:Judge(?:\s+critique)?|審判(?:評価)?|批評|評価)\s*[:：]\s*(.*)$/i); if(inline) return {inline:inline[1]}; if(/^\s*#*\s*(?:Judge(?:\s+critique)?|審判(?:評価)?|批評|評価)\s*$/i.test(text)) return {inline:''}; const header=judgeProfile&&parserSpeakerHeader(text,[judgeProfile]); const participantHeader=parserSpeakerHeader(text,participantProfiles); return header&&(!participantHeader||participantHeader.profile==='judge') ? {inline:''} : null; }
function parseStructuredLog(lines,participantProfiles,judgeProfile){ const turns=[]; const critiqueLines=[]; let activeSpeaker=''; let activeLines=[]; let inCritique=false; let afterSystem=false; const flush=()=>{ const body=activeLines.join('\n').trim(); if(activeSpeaker&&body) turns.push([activeSpeaker,body]); activeSpeaker=''; activeLines=[]; }; for(let index=0;index<lines.length;index+=1){ const line=lines[index]; if(inCritique){ if(parserIsSystemLine(line)||parserIsProgressLine(line)) continue; critiqueLines.push(line); continue; } const judge=parserJudgeMarker(line,judgeProfile,participantProfiles); if(judge){ flush(); inCritique=true; afterSystem=false; if(judge.inline) critiqueLines.push(judge.inline); continue; } if(parserIsSystemLine(line)){ flush(); afterSystem=true; continue; } if(afterSystem&&parserIsProgressLine(line)){ afterSystem=false; continue; } const header=parserSpeakerHeader(line,participantProfiles); if(header){ flush(); activeSpeaker=header.speaker; afterSystem=false; continue; } if(afterSystem&&!line.trim()) continue; afterSystem=false; if(activeSpeaker) activeLines.push(line); } flush(); return {turns,critique:critiqueLines.join('\n').trim()}; }
function parseLegacyLog(lines){ const turns=[]; const critiqueLines=[]; let activeSpeaker=''; let activeLines=[]; let inCritique=false; const flush=()=>{ const body=activeLines.join('\n').trim(); if(activeSpeaker&&body) turns.push([activeSpeaker,body]); activeSpeaker=''; activeLines=[]; }; for(const line of lines){ if(inCritique){ critiqueLines.push(line); continue; } const judge=parserJudgeMarker(line,null); if(judge){ flush(); inCritique=true; if(judge.inline) critiqueLines.push(judge.inline); continue; } const match=String(line||'').match(/^\s*(?:\[?([^\]:：]{2,40})\]?)[：:]\s*(.*)$/); if(match&&!/^https?/.test(match[2])){ flush(); activeSpeaker=match[1].trim(); activeLines=[match[2]]; continue; } if(activeSpeaker) activeLines.push(line); } flush(); return {turns,critique:critiqueLines.join('\n').trim()}; }
function parseForm(){ const rawInput=document.querySelector('#raw').value; const raw=rawInput.trim(); const modelA=document.querySelector('#model-a').value.trim(); const modelB=document.querySelector('#model-b').value.trim(); const participants=[modelA,modelB]; const judgeDetail=document.querySelector('#judge').value.trim(); const judgeProvider=document.querySelector('#judge-provider')?.selectedOptions?.[0]?.textContent.trim()||''; const judge=judgeDetail?(judgeProvider?judgeProvider+' / '+judgeDetail:judgeDetail):''; const lines=raw.split(/\r?\n/); const participantProfiles=[parserProfile('model-a','A'),parserProfile('model-b','B')].filter(profile=>profile.detail); const judgeProfile=parserProfile('judge','judge'); const hasStructuredHeaders=lines.some(line=>parserSpeakerHeader(line,participantProfiles)); const parsed=hasStructuredHeaders?parseStructuredLog(lines,participantProfiles,judgeProfile):parseLegacyLog(lines); return { title:document.querySelector('#title').value.trim(), date:document.querySelector('#date').value.trim(), model_a:modelA, model_b:modelB, participants, judge, turns:parsed.turns, critique:parsed.critique, memo:document.querySelector('#memo').value.trim() }; }
function preview(item,error=''){ const box=document.querySelector('#preview'); box.hidden=false; box.innerHTML=`<h2>Preview</h2>${error?`<p class="meta">${escapeHTML(error)}</p>`:''}<p><strong>${escapeHTML(item.title||'Untitled')}</strong> <span class="meta">${escapeHTML(item.date||'')}</span></p><p class="log-meta">${item.participants.map(modelHTML).join(' · ')} / Judge: ${modelHTML(item.judge||'')}</p>${item.turns.map((t,index)=>`<div class="turn"><div class="turn-speaker">${modelHTML(t[0])}</div><div class="turn-body">${escapeHTML(t[1])}</div>${turnSystemHTML(t,index,item.turns)}</div>`).join('')||'<p class="empty">No turns detected yet.</p>'}${item.critique?`<div class="subsection judge-critique"><h3>Judge critique</h3><div class="judge-critique-speaker"><span class="meta">Judge</span> ${modelHTML(item.judge)}</div>${critiqueHTML(item.critique)}</div>`:''}`; }
 function critiqueHTML(value){ const paragraphs=String(value||'').split(/\n{2,}/).map(paragraph=>paragraph.trim()).filter(Boolean); return paragraphs.map(paragraph=>`<p>${escapeHTML(paragraph)}</p>`).join('')||'<p class="empty">No judge critique detected.</p>'; }
function themeIcon(theme){ return theme==='light' ? '<svg class="theme-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"></path></svg>' : '<svg class="theme-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.2A8 8 0 0 1 8.8 4 8.5 8.5 0 1 0 20 15.2Z"></path></svg>'; }
function setTheme(theme){ document.documentElement.classList.toggle('light',theme==='light'); const toggle=document.querySelector('#theme-toggle'); toggle.innerHTML=themeIcon(theme); toggle.setAttribute('aria-label',theme==='light'?'Light theme':'Dark theme'); toggle.title=theme==='light'?'Sol':'Luna'; localStorage.setItem('ai-debate-theme',theme); }
document.querySelector('#theme-toggle').onclick=()=>setTheme(document.documentElement.classList.contains('light')?'dark':'light');
setTheme(localStorage.getItem('ai-debate-theme') || (matchMedia('(prefers-color-scheme: light)').matches?'light':'dark')); window.addEventListener('hashchange',render); render(); initializeAuth().then(loadPublicLogs);
